baseurl = "https://leninau.github.io/Blog_Numerico/"
languageCode = "es-es"
defaultContentLanguage = "es-es"
title = "Proyecto Innovación Educativa MOOC UNAM Lenin Echavarría"
theme = "charaka-hugo-theme"
copyright = "&copy; <a href=\"https://github.com/leninau\">Lenin Echavarría</a> 2020"
disqusShortname = "blog-numerico"
googleAnalytics = ""
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

[author]
  name = "Lenin Echavarría"
  homepage = "https://github.com/leninau"

[params.highlight]
  style = "zenburn"

[params.share]
  enabled = "true"


